### ISSUE TITLE
Add docs/demo with ReadTheDocs

### ISSUE THREAD

**Issue by bollwyvl** [agoose77/jupyterlab-markup#65]
It would be nice to use [ReadTheDocs](https://readthedocs.org/) to get a documentation site up. This could include some generated API docs (especially for the plugin API) for the typescript side of the house, as well as provide more concrete examples of any built-in (or at least [monorepo'd](https://github.com/agoose77/jupyterlab-markup/issues/40)) plugins.

With a bit more work, this could also use [jupyterlite](https://github.com/jupyterlite/jupyterlite) (or [jupyterlite-sphinx](https://github.com/jupyterlite/jupyterlite-sphinx/) and get per-PR-push previews deployed.

## Tasks

- baseline
  - in RTD web ui
    - [x] reserve appropriate site name, e.g `jupyterlab-markup.rtfd.io`
    - [x] set up preview builds
  - in a PR 
    - [x] create `.readthedocs.yml`
    - [x] capture docs build deps
    - [x] create `docs/conf.py`
    - [x] create some basic docs examples
- advanced
  - [x] create `environment.yml` (so the nodejs version can be pinned along with everything else)
  - [ ] set up typedoc
  - [x] use jupyterlite
  - [ ] add link-checking
  - [ ] automate some screenshots with galata/robot

**Comment by bollwyvl** [comment]
@agoose77 if you fire up the RTD config i can PR the rest!

**Comment by agoose77** [comment]
Thanks @bollwyvl, done!

**Comment by bollwyvl** [comment]
Will get a PR up sometime later today.
